site_name: Forensia Digital
theme: minty
nav:
  - Inicio: index.md
  - Introducción: introduccion.md
  - Proceso: proceso.md
  - Herramientas: herramientas.md
  - Recursos: recursos.md
  - Acerca de: about.md
